name: ci-ui-test
on:
  push:
    branches: [dev, master]
    paths: ["src/ui/**"]
  pull_request:
    branches: [dev, master]
    paths: ["src/ui/**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Install dependencies
        run: npm ci -w writer-ui

      - name: Run tests
        run: npm test -w writer-ui
