name: publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - 'v[0-9]+.[0-9]+.[0-9]+[a-z0-9]*'

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@v4

            - name: Install poetry
              run: pipx install poetry

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                cache: 'poetry'

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "22.x"
                cache: npm

            - name: install python3 environment
              run: poetry install --with build

            - name: install ci dependencies and generate code
              run: poetry run alfred install.ci

            - name: publish on pypi
              run: |
                poetry run alfred publish.pypi
              env:
                  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
